//! Generated terminal compatibility matrix (quadraui#829, "Terminal-honest
//! #5"). Read this when:
//!
//! - you're adding a new terminal-protocol pty fixture to
//!   `tests/tui_pty_smoke.rs` and want to know how to get it into the
//!   published matrix;
//! - `readme_terminal_matrix_matches_generated` (below) is failing in CI and
//!   you need to know how to fix it (see that test's panic message — it
//!   names the exact command);
//! - you're deciding whether a multiplexer/colour-depth/mouse-mode/
//!   key-protocol combination is something quadraui actually verifies, or
//!   just claims.
//!
//! ## Why this exists
//!
//! quadraui#787's Terminal-honest epic exists because a terminal feature
//! that "should" work and a terminal feature that is *observed* to work are
//! different claims, and conflating them is how #293 (SGR mouse leaking
//! into input), #826 (unconditional truecolor on a 256-colour terminal) and
//! #827 (kitty protocol flags never checked) all shipped silently broken.
//! `tests/tui_pty_smoke.rs` closes that gap for a handful of
//! multiplexer/colour-depth/mouse-mode/key-protocol combinations by
//! spawning a real example binary in a real pty and reading the literal
//! bytes it emits. This file turns *that* — the actual, checked-in pty
//! fixtures — into a published table, instead of a claim someone typed by
//! hand into the README (see quadraui#798, which exists because a
//! hand-written doc drifted from the code it described).
//!
//! ## How "generated" is enforced here
//!
//! Three things anchor every row to something mechanically checkable,
//! rather than to a sentence a human could get wrong and never notice:
//!
//! 1. Every [`Status::Verified`] row names the exact `fn` in
//!    `tests/tui_pty_smoke.rs` that backs it
//!    (`every_verified_rows_test_fn_exists_in_the_pty_tier` greps the real
//!    source for it — a renamed/removed pty test fails this file, not just
//!    silently going stale).
//! 2. [`quadraui::ColorDepth`]'s three variants are matched exhaustively
//!    (no wildcard arm) against this matrix's colour-depth rows
//!    (`every_colordepth_variant_has_a_verified_matrix_row`) — a fourth
//!    variant is a compile error here until the matrix grows a row for it.
//! 3. `readme_terminal_matrix_matches_generated` regenerates the table from
//!    [`all_rows`] and fails if the committed block between the
//!    `TERMINAL_MATRIX` markers in the root `README.md` differs by so much
//!    as a character — the same guard shape `tests/readme_truth.rs` (#798)
//!    uses for the rest of the README.
//!
//! What this cannot do: notice a terminal-protocol claim this file's author
//! never thought to add a row for. It only keeps the rows that exist
//! honest — extend [`all_rows`] (and the pty tier itself) when a new
//! combination gets a real fixture.
//!
//! ## Regenerating the README block
//!
//! ```sh
//! cargo test -p quadraui --test terminal_matrix -- --ignored print_terminal_matrix --nocapture
//! ```
//!
//! Replace everything between `<!-- TERMINAL_MATRIX:START -->` and
//! `<!-- TERMINAL_MATRIX:END -->` in the root `README.md` with that
//! command's output, verbatim. Never hand-edit the table itself — that is
//! exactly the drift this file exists to prevent.

use std::fs;
use std::path::PathBuf;

/// Repo root — `quadraui/`'s parent, where the root `README.md` lives.
fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("quadraui crate dir always has a parent (the repo root)")
        .to_path_buf()
}

/// `quadraui/`'s own crate dir (this test's `CARGO_MANIFEST_DIR`).
fn crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(path: PathBuf) -> String {
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()))
}

fn root_readme() -> String {
    read(repo_root().join("README.md"))
}

/// The pty tier's own source — the ground truth every [`Status::Verified`]
/// row is checked against.
fn pty_smoke_src() -> String {
    read(crate_root().join("tests/tui_pty_smoke.rs"))
}

/// Marks the start of the generated block inside the root `README.md`.
/// Kept as one `const` (rather than inlined at each call site) so the exact
/// text can't drift between the reader and the writer.
const MATRIX_START: &str = "<!-- TERMINAL_MATRIX:START — generated by \
    quadraui/tests/terminal_matrix.rs (quadraui#829); do not hand-edit, see \
    that file's module doc for how to regenerate -->";
const MATRIX_END: &str = "<!-- TERMINAL_MATRIX:END -->";

/// How a row's claim is backed. No row is ever left without one of these —
/// that's acceptance item 3 of quadraui#829 ("no blank cell implying
/// support"), enforced structurally: [`Row`] has no way to express "no
/// status".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Status {
    /// A real `tests/tui_pty_smoke.rs` pty fixture observed this.
    Verified,
    /// Verified — as a *negative* fact, from a source or doc citation
    /// (crossterm's Windows implementation, a vendored dependency's own
    /// code) rather than a pty fixture, because no pty fixture can exist
    /// for it in this repo's CI (no Windows console host on Linux CI, etc).
    KnownUnsupported,
    /// Nobody has checked. Named honestly rather than left blank.
    Untested,
}

impl Status {
    fn label(self) -> &'static str {
        match self {
            Status::Verified => "✅ verified",
            Status::KnownUnsupported => "🚫 known-unsupported",
            Status::Untested => "❔ untested",
        }
    }
}

/// One row of the published matrix.
struct Row {
    axis: &'static str,
    condition: &'static str,
    status: Status,
    /// For [`Status::Verified`] rows: the exact `fn` name in
    /// `tests/tui_pty_smoke.rs` this row rests on. `None` for
    /// `KnownUnsupported`/`Untested` rows, which cite a doc/source instead
    /// (see `verified_by`).
    test_fn: Option<&'static str>,
    /// The `Verified by` column's free text: `module::test_fn` for a
    /// `Verified` row (kept in sync with `test_fn` by
    /// `every_verified_rows_test_fn_exists_in_the_pty_tier`), or a citation
    /// for why the row isn't pty-verified.
    verified_by: &'static str,
}

/// Colour-depth axis — `tests/tui_pty_smoke.rs`'s `sgr_color_depth` module
/// (quadraui#826). Exhaustiveness against `quadraui::ColorDepth`'s three
/// variants is checked by `every_colordepth_variant_has_a_verified_matrix_row`.
fn color_depth_rows() -> Vec<Row> {
    vec![
        Row {
            axis: "Colour depth",
            condition: "`COLORTERM=truecolor` — 24-bit",
            status: Status::Verified,
            test_fn: Some("tui_pipeline_with_colorterm_truecolor_is_byte_identical_to_before"),
            verified_by:
                "sgr_color_depth::tui_pipeline_with_colorterm_truecolor_is_byte_identical_to_before",
        },
        Row {
            axis: "Colour depth",
            condition: "`TERM` contains `256color`, no `COLORTERM` — 256-indexed",
            status: Status::Verified,
            test_fn: Some("tui_pipeline_under_256color_term_emits_indexed_sgr_not_truecolor"),
            verified_by:
                "sgr_color_depth::tui_pipeline_under_256color_term_emits_indexed_sgr_not_truecolor",
        },
        Row {
            axis: "Colour depth",
            condition: "`TERM=xterm` (no `256color`, no `COLORTERM`) — 16-colour fallback",
            status: Status::Verified,
            test_fn: Some("tui_pipeline_under_plain_xterm_emits_ansi16_sgr"),
            verified_by: "sgr_color_depth::tui_pipeline_under_plain_xterm_emits_ansi16_sgr",
        },
    ]
}

/// Mouse-mode axis — `no_mouse` module (quadraui#828) plus the `tui_chat`
/// SGR mouse-motion fixtures (#293).
fn mouse_mode_rows() -> Vec<Row> {
    vec![
        Row {
            axis: "Mouse mode",
            condition: "Default `RunConfig` — capture negotiated (`?1000h` et al. sent)",
            status: Status::Verified,
            test_fn: Some("tui_split_negotiates_mouse_capture_by_default"),
            verified_by: "no_mouse::tui_split_negotiates_mouse_capture_by_default",
        },
        Row {
            axis: "Mouse mode",
            condition: "`RunConfig::no_mouse()` — capture withheld, keyboard-only stays operable",
            status: Status::Verified,
            test_fn: Some(
                "tui_no_mouse_never_negotiates_mouse_capture_and_stays_keyboard_operable",
            ),
            verified_by:
                "no_mouse::tui_no_mouse_never_negotiates_mouse_capture_and_stays_keyboard_operable",
        },
        Row {
            axis: "Mouse mode",
            condition:
                "SGR mouse-motion report decodes without leaking into a focused text input (#293)",
            status: Status::Verified,
            test_fn: Some("tui_chat_sgr_mouse_motion_does_not_leak_into_input"),
            verified_by: "tui_chat_sgr_mouse_motion_does_not_leak_into_input",
        },
        Row {
            axis: "Mouse mode",
            condition: "Escape glued to an SGR motion report in one `write()` (#293 race)",
            status: Status::Verified,
            test_fn: Some("tui_chat_escape_glued_to_sgr_motion_in_one_write_does_not_leak"),
            verified_by: "tui_chat_escape_glued_to_sgr_motion_in_one_write_does_not_leak",
        },
    ]
}

/// Key-protocol (kitty) axis — `kitty_keyboard_protocol` module
/// (quadraui#827) for the two pty-verified rows; every other row mirrors
/// `docs/KITTY_KEYBOARD_PROTOCOL.md`'s degrade table, which is the
/// hand-maintained per-environment detail this matrix's compact rows
/// summarise (read that doc for the full reasoning behind each citation).
fn kitty_protocol_rows() -> Vec<Row> {
    vec![
        Row {
            axis: "Key protocol (kitty)",
            condition: "`TERM=xterm-kitty`, live query unanswered — env-heuristic fallback fires",
            status: Status::Verified,
            test_fn: Some("tui_pipeline_under_kitty_term_pushes_enhancement_flags"),
            verified_by: "kitty_keyboard_protocol::tui_pipeline_under_kitty_term_pushes_enhancement_flags",
        },
        Row {
            axis: "Key protocol (kitty)",
            condition: "Plain `TERM=xterm-256color`, no kitty/WezTerm/foot signal",
            status: Status::Verified,
            test_fn: Some("tui_pipeline_under_plain_term_does_not_push_enhancement_flags"),
            verified_by: "kitty_keyboard_protocol::tui_pipeline_under_plain_term_does_not_push_enhancement_flags",
        },
        Row {
            axis: "Key protocol (kitty)",
            condition: "Real kitty terminal, live query actually answered",
            status: Status::Untested,
            test_fn: None,
            verified_by: "no kitty binary in CI — docs/KITTY_KEYBOARD_PROTOCOL.md degrade table",
        },
        Row {
            axis: "Key protocol (kitty)",
            condition: "WezTerm / foot / Alacritty ≥0.12",
            status: Status::Untested,
            test_fn: None,
            verified_by: "unit-tested heuristic only, no real binary in CI — docs/KITTY_KEYBOARD_PROTOCOL.md",
        },
        Row {
            axis: "Key protocol (kitty)",
            condition: "Windows Terminal / any Windows console host",
            status: Status::KnownUnsupported,
            test_fn: None,
            verified_by: "crossterm-0.29.0's Windows `supports_keyboard_enhancement()` is an \
                unconditional `Ok(false)` — docs/KITTY_KEYBOARD_PROTOCOL.md",
        },
        Row {
            axis: "Key protocol (kitty)",
            condition: "Terminal.app (macOS)",
            status: Status::Untested,
            test_fn: None,
            verified_by: "no macOS runner exercises the TUI backend under Terminal.app — \
                docs/KITTY_KEYBOARD_PROTOCOL.md",
        },
        Row {
            axis: "Key protocol (kitty)",
            condition: "Serial console",
            status: Status::Untested,
            test_fn: None,
            verified_by: "no serial hardware/emulation in CI — docs/KITTY_KEYBOARD_PROTOCOL.md",
        },
    ]
}

/// Multiplexer axis. Nothing here is pty-verified: this repo's CI has no
/// tmux/mosh binary to drive an automated fixture against (the same gap
/// `docs/KITTY_KEYBOARD_PROTOCOL.md`'s tmux/mosh rows and
/// `docs/CLIPBOARD.md`'s tmux section both document independently). Listed
/// explicitly, as `Untested`, rather than omitted — omitting it is exactly
/// the "blank cell implying support" quadraui#829 exists to rule out.
fn multiplexer_rows() -> Vec<Row> {
    vec![
        Row {
            axis: "Multiplexer",
            condition: "tmux, no passthrough configured (default)",
            status: Status::Untested,
            test_fn: None,
            verified_by:
                "no tmux binary in CI — docs/KITTY_KEYBOARD_PROTOCOL.md tmux row, docs/CLIPBOARD.md",
        },
        Row {
            axis: "Multiplexer",
            condition: "tmux, `set-clipboard on` + `allow-passthrough on`",
            status: Status::Untested,
            test_fn: None,
            verified_by: "no tmux binary in CI — docs/CLIPBOARD.md tmux knobs",
        },
        Row {
            axis: "Multiplexer",
            condition: "mosh",
            status: Status::Untested,
            test_fn: None,
            verified_by: "no mosh available in CI — docs/KITTY_KEYBOARD_PROTOCOL.md",
        },
    ]
}

/// Every row in the published matrix, in table order.
fn all_rows() -> Vec<Row> {
    let mut rows = Vec::new();
    rows.extend(multiplexer_rows());
    rows.extend(color_depth_rows());
    rows.extend(mouse_mode_rows());
    rows.extend(kitty_protocol_rows());
    rows
}

/// Render `rows` as the exact markdown table this file publishes into the
/// root `README.md`.
fn render_matrix(rows: &[Row]) -> String {
    let mut out = String::new();
    out.push_str("| Axis | Condition | Status | Verified by |\n");
    out.push_str("|---|---|---|---|\n");
    for row in rows {
        out.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            row.axis,
            row.condition,
            row.status.label(),
            row.verified_by
        ));
    }
    out
}

#[test]
fn every_verified_rows_test_fn_exists_in_the_pty_tier() {
    let src = pty_smoke_src();
    for row in all_rows() {
        if row.status != Status::Verified {
            continue;
        }
        let name = row.test_fn.unwrap_or_else(|| {
            panic!(
                "matrix row {:?} ({:?}) is Status::Verified but has no test_fn — every \
                 Verified row must name the pty test that backs it",
                row.axis, row.condition
            )
        });
        let needle = format!("fn {name}(");
        assert!(
            src.contains(&needle),
            "matrix row {:?} ({:?}) claims verification by `{name}`, but \
             tests/tui_pty_smoke.rs has no `fn {name}(` — the pty test was renamed or \
             removed. Update this matrix (and README.md's generated block — see this \
             file's module doc) in the same PR that changes the pty tier.",
            row.axis,
            row.condition
        );
    }
}

#[test]
fn every_colordepth_variant_has_a_verified_matrix_row() {
    // Exhaustive match — no wildcard arm — over `quadraui::ColorDepth`. A
    // fourth variant is a compile error here, which is what forces this
    // matrix to grow a row for it in the same PR rather than silently
    // describing only three of four depths forever.
    fn expected_test_fn(d: quadraui::ColorDepth) -> &'static str {
        use quadraui::ColorDepth::*;
        match d {
            Ansi16 => "tui_pipeline_under_plain_xterm_emits_ansi16_sgr",
            Indexed256 => "tui_pipeline_under_256color_term_emits_indexed_sgr_not_truecolor",
            TrueColor => "tui_pipeline_with_colorterm_truecolor_is_byte_identical_to_before",
        }
    }
    let rows = all_rows();
    for expected in [
        expected_test_fn(quadraui::ColorDepth::Ansi16),
        expected_test_fn(quadraui::ColorDepth::Indexed256),
        expected_test_fn(quadraui::ColorDepth::TrueColor),
    ] {
        assert!(
            rows.iter()
                .any(|r| r.status == Status::Verified && r.test_fn == Some(expected)),
            "no Verified matrix row cites `{expected}` — a ColorDepth variant is missing \
             its colour-depth row"
        );
    }
}

#[test]
fn readme_terminal_matrix_matches_generated() {
    let readme = root_readme();
    let start = readme.find(MATRIX_START).unwrap_or_else(|| {
        panic!(
            "root README.md is missing the `{MATRIX_START}` marker — the generated \
             terminal compatibility matrix (quadraui#829) has nowhere to go. Add both \
             markers (see quadraui/tests/terminal_matrix.rs's module doc) and re-run this \
             test to see the block to paste between them."
        )
    });
    let after_start = start + MATRIX_START.len();
    let end = readme[after_start..].find(MATRIX_END).unwrap_or_else(|| {
        panic!(
            "root README.md has a `{MATRIX_START}` marker but no matching \
             `{MATRIX_END}` — add the closing marker."
        )
    }) + after_start;

    let committed = readme[after_start..end].trim();
    let generated = render_matrix(&all_rows());

    assert_eq!(
        committed,
        generated.trim(),
        "README.md's terminal compatibility matrix (between the TERMINAL_MATRIX markers) \
         does not match what quadraui/tests/terminal_matrix.rs generates from the pty \
         tier's actual tests. Regenerate it — never hand-edit the table:\n\n  cargo test \
         -p quadraui --test terminal_matrix -- --ignored print_terminal_matrix --nocapture\n\n\
         — then replace everything between the markers with that command's output, \
         verbatim. This is the same drift quadraui#798 exists to prevent for the rest of \
         the README (see tests/readme_truth.rs)."
    );
}

/// Not part of the normal suite — prints the exact block to paste into
/// `README.md` between the `TERMINAL_MATRIX` markers. See this file's
/// module doc, "Regenerating the README block".
#[test]
#[ignore = "prints the generated matrix for pasting into README.md; run explicitly, see module doc"]
fn print_terminal_matrix() {
    print!("{}", render_matrix(&all_rows()));
}
